### ISSUE TITLE
Loading model error

### ISSUE THREAD

**Issue by LeonJWH** [ckiplab/ckip-transformers#8]
When I tried to use CKIP-transformer to perform Chinese NER task pytorch. But when I loaded the model of level 3, The follow error occurs:
Traceback (most recent call last):
  File "ner.py", line 3, in <module>
    ner_driver = CkipNerChunker(level=3, device=0)
  File "/home/nieyang/anaconda3/envs/huggingface/lib/python3.6/site-packages/ckip_transformers/nlp/driver.py", line 224, in __init__
    super().__init__(model_name=model_name, **kwargs)
  File "/home/nieyang/anaconda3/envs/huggingface/lib/python3.6/site-packages/ckip_transformers/nlp/util.py", line 64, in __init__
    self.model = AutoModelForTokenClassification.from_pretrained(model_name)
  File "/home/nieyang/anaconda3/envs/huggingface/lib/python3.6/site-packages/transformers/models/auto/auto_factory.py", line 360, in from_pretrained
    pretrained_model_name_or_path, *model_args, config=config, **kwargs
  File "/home/nieyang/anaconda3/envs/huggingface/lib/python3.6/site-packages/transformers/modeling_utils.py", line 1066, in from_pretrained
    f"Unable to load weights from pytorch checkpoint file for '{pretrained_model_name_or_path}' "
OSError: Unable to load weights from pytorch checkpoint file for 'ckiplab/bert-base-chinese-ner' at '/home/nieyang/.cache/huggingface/transformers/46785b95696d8e6a5004a6a73fcee887d60745a5872af82ca7599b9470554ce3.bdaa5056a5c748eca59fe2c7eef8fa2d034f5092fc84ce6b008c27ddf6f0025c'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.

 So I added the flag `from_tf=True` to `self.model = AutoModelForTokenClassification.from_pretrained(model_name)` in **ckip_transformers/nlp/util.py**, but it then cames out that the model name is wrong.

So can you help me with this?

**Comment by emfomy** [comment]
Our models are PyTorch's not TensorFlow. You should not use `from_tf=True`.

What versions of PyTorch & transformers are you using?

**Comment by LeonJWH** [comment]
Thank you for your reply!
I use PyTorch='1.6.0+cu101' and transformers=4.5.1.  I tried to use `level=2`, everything  goes well now, but error occurs when setting `level=3`.

**Comment by emfomy** [comment]
I can't reproduce the error 😢.
Maybe the cached file is corrupted.
Can you remove the cached files (in /home/nieyang/.cache/huggingface/transformers/) and try it again?
